env:
  es6: true
  node: true
extends: ['airbnb-base', 'prettier']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  { 'import/prefer-default-export': 'off', 'import/no-default-export': 'error' }
