import { FetchFunction } from './types';

import * as apt from './command-defs/apt';
import { fetchBrew } from './command-defs/brew';
import * as daemontools from './command-defs/daemontools';
import { fetchDocker } from './command-defs/docker';
import * as ffmpeg from './command-defs/ffmpeg';
import { fetchGit } from './command-defs/git';
import * as gnuCoreutils from './command-defs/gnu-coreutils';
import { fetchGo } from './command-defs/go';
import * as graphviz from './command-defs/graphviz';
import * as imagemagick from './command-defs/imagemagick';
import { fetchJq } from './command-defs/jq';
import * as mysql from './command-defs/mysql';
import { fetchPerl } from './command-defs/perl';
import { fetchPython } from './command-defs/python';
import { fetchRsync } from './command-defs/rsync';
import { fetchSshuttle } from './command-defs/sshuttle';
import { fetchTerraform } from './command-defs/terraform';
import { fetchYarn } from './command-defs/yarn';

export const baseCommandToFetchFunction = new Map<string, FetchFunction>([
  ['apt-cache', apt.fetchAptCache],
  ['apt-get', apt.fetchAptGet],
  ['arch', gnuCoreutils.fetchArch],
  ['b2sum', gnuCoreutils.fetchB2sum],
  ['base32', gnuCoreutils.fetchBase32],
  ['base64', gnuCoreutils.fetchBase64],
  ['basename', gnuCoreutils.fetchBasename],
  ['basenc', gnuCoreutils.fetchBasenc],
  ['brew', fetchBrew],
  ['cat', gnuCoreutils.fetchCat],
  ['chcon', gnuCoreutils.fetchChcon],
  ['chgrp', gnuCoreutils.fetchChgrp],
  ['chmod', gnuCoreutils.fetchChmod],
  ['chown', gnuCoreutils.fetchChown],
  ['chroot', gnuCoreutils.fetchChroot],
  ['cksum', gnuCoreutils.fetchCksum],
  ['comm', gnuCoreutils.fetchComm],
  ['coreutils', gnuCoreutils.fetchCoreutils],
  ['cp', gnuCoreutils.fetchCp],
  ['csplit', gnuCoreutils.fetchCsplit],
  ['cut', gnuCoreutils.fetchCut],
  ['date', gnuCoreutils.fetchDate],
  ['dd', gnuCoreutils.fetchDd],
  ['df', gnuCoreutils.fetchDf],
  ['dir', gnuCoreutils.fetchDir],
  ['dircolors', gnuCoreutils.fetchDircolors],
  ['dirname', gnuCoreutils.fetchDirname],
  ['docker', fetchDocker],
  ['dot', graphviz.fetchDot],
  ['du', gnuCoreutils.fetchDu],
  ['echo', gnuCoreutils.fetchEcho],
  ['env', gnuCoreutils.fetchEnv],
  ['expand', gnuCoreutils.fetchExpand],
  ['expr', gnuCoreutils.fetchExpr],
  ['factor', gnuCoreutils.fetchFactor],
  ['false', gnuCoreutils.fetchFalse],
  ['ffmpeg', ffmpeg.fetchFfmpeg],
  ['ffplay', ffmpeg.fetchFfplay],
  ['ffprobe', ffmpeg.fetchFfprobe],
  ['fmt', gnuCoreutils.fetchFmt],
  ['fold', gnuCoreutils.fetchFold],
  ['git', fetchGit],
  ['go', fetchGo],
  ['groups', gnuCoreutils.fetchGroups],
  ['head', gnuCoreutils.fetchHead],
  ['hostid', gnuCoreutils.fetchHostid],
  ['hostname', gnuCoreutils.fetchHostname],
  ['id', gnuCoreutils.fetchId],
  ['install', gnuCoreutils.fetchInstall],
  ['join', gnuCoreutils.fetchJoin],
  ['jq', fetchJq],
  ['kill', gnuCoreutils.fetchKill],
  ['link', gnuCoreutils.fetchLink],
  ['ln', gnuCoreutils.fetchLn],
  ['logname', gnuCoreutils.fetchLogname],
  ['ls', gnuCoreutils.fetchLs],
  ['magick', imagemagick.fetchMagick],
  ['magick-script', imagemagick.fetchMagickScript],
  ['md5sum', gnuCoreutils.fetchMd5sum],
  ['mkdir', gnuCoreutils.fetchMkdir],
  ['mkfifo', gnuCoreutils.fetchMkfifo],
  ['mknod', gnuCoreutils.fetchMknod],
  ['mktemp', gnuCoreutils.fetchMktemp],
  ['mv', gnuCoreutils.fetchMv],
  ['mysql', mysql.fetchMysql],
  ['mysqladmin', mysql.fetchMysqladmin],
  ['mysqlcheck', mysql.fetchMysqlcheck],
  ['mysqldump', mysql.fetchMysqldump],
  ['mysqlimport', mysql.fetchMysqlimport],
  ['mysqlpump', mysql.fetchMysqlpump],
  ['mysqlshow', mysql.fetchMysqlshow],
  ['mysqlslap', mysql.fetchMysqlslap],
  ['nice', gnuCoreutils.fetchNice],
  ['nl', gnuCoreutils.fetchNl],
  ['nohup', gnuCoreutils.fetchNohup],
  ['nproc', gnuCoreutils.fetchNproc],
  ['numfmt', gnuCoreutils.fetchNumfmt],
  ['od', gnuCoreutils.fetchOd],
  ['paste', gnuCoreutils.fetchPaste],
  ['pathchk', gnuCoreutils.fetchPathchk],
  ['perl', fetchPerl],
  ['pinky', gnuCoreutils.fetchPinky],
  ['pr', gnuCoreutils.fetchPr],
  ['printenv', gnuCoreutils.fetchPrintenv],
  ['printf', gnuCoreutils.fetchPrintf],
  ['ptx', gnuCoreutils.fetchPtx],
  ['pwd', gnuCoreutils.fetchPwd],
  ['python', fetchPython],
  ['readlink', gnuCoreutils.fetchReadlink],
  ['realpath', gnuCoreutils.fetchRealpath],
  ['rm', gnuCoreutils.fetchRm],
  ['rmdir', gnuCoreutils.fetchRmdir],
  ['rsync', fetchRsync],
  ['runcon', gnuCoreutils.fetchRuncon],
  ['seq', gnuCoreutils.fetchSeq],
  ['setlock', daemontools.fetchSetlock],
  ['sha1sum', gnuCoreutils.fetchSha1sum],
  ['sha224sum', gnuCoreutils.fetchSha224sum],
  ['sha256sum', gnuCoreutils.fetchSha256sum],
  ['sha384sum', gnuCoreutils.fetchSha384sum],
  ['sha512sum', gnuCoreutils.fetchSha512sum],
  ['shred', gnuCoreutils.fetchShred],
  ['shuf', gnuCoreutils.fetchShuf],
  ['sleep', gnuCoreutils.fetchSleep],
  ['softlimit', daemontools.fetchSoftlimit],
  ['sort', gnuCoreutils.fetchSort],
  ['split', gnuCoreutils.fetchSplit],
  ['sshuttle', fetchSshuttle],
  ['stat', gnuCoreutils.fetchStat],
  ['stdbuf', gnuCoreutils.fetchStdbuf],
  ['stty', gnuCoreutils.fetchStty],
  ['sum', gnuCoreutils.fetchSum],
  ['svc', daemontools.fetchSvc],
  ['sync', gnuCoreutils.fetchSync],
  ['tac', gnuCoreutils.fetchTac],
  ['tail', gnuCoreutils.fetchTail],
  ['tee', gnuCoreutils.fetchTee],
  ['terraform', fetchTerraform],
  ['test', gnuCoreutils.fetchTest],
  ['timeout', gnuCoreutils.fetchTimeout],
  ['touch', gnuCoreutils.fetchTouch],
  ['tr', gnuCoreutils.fetchTr],
  ['true', gnuCoreutils.fetchTrue],
  ['truncate', gnuCoreutils.fetchTruncate],
  ['tsort', gnuCoreutils.fetchTsort],
  ['tty', gnuCoreutils.fetchTty],
  ['uname', gnuCoreutils.fetchUname],
  ['unexpand', gnuCoreutils.fetchUnexpand],
  ['uniq', gnuCoreutils.fetchUniq],
  ['unlink', gnuCoreutils.fetchUnlink],
  ['uptime', gnuCoreutils.fetchUptime],
  ['users', gnuCoreutils.fetchUsers],
  ['vdir', gnuCoreutils.fetchVdir],
  ['wc', gnuCoreutils.fetchWc],
  ['who', gnuCoreutils.fetchWho],
  ['whoami', gnuCoreutils.fetchWhoami],
  ['yarn', fetchYarn],
  ['yes', gnuCoreutils.fetchYes],
]);
